name: "Install dependencies"
description: "Run yarn install --immutable on every job and get cached lockfile"
runs:
  using: composite
  steps:
    - name: Get Yarn Cache
      id: yarn-cache
      shell: bash
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - uses: actions/cache@v3
      id: cache-deps
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install Packages
      shell: bash
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: yarn install --immutable
