import {
  backgroundColor,
  BackgroundColorProps,
  borderColor,
  BorderColorProps,
  borderRadius,
  BorderRadiusProps,
  borderStyle,
  BorderStyleProps,
  borderWidth,
  BorderWidthProps,
  bottom,
  BottomProps,
  color,
  ColorProps,
  colorStyle,
  ColorStyleProps,
  display,
  DisplayProps,
  height,
  HeightProps,
  left,
  LeftProps,
  maxWidth,
  MaxWidthProps,
  minWidth,
  MinWidthProps,
  position,
  PositionProps,
  right,
  RightProps,
  space,
  SpaceProps,
  top,
  TopProps,
  width,
  WidthProps,
  zIndex,
  ZIndexProps,
} from 'styled-system'
import styled from 'styled-components'

export interface BoxProps
  extends PositionProps,
    TopProps,
    BottomProps,
    LeftProps,
    RightProps,
    WidthProps,
    HeightProps,
    MaxWidthProps,
    MinWidthProps,
    SpaceProps,
    ColorProps,
    ColorStyleProps,
    DisplayProps,
    BackgroundColorProps,
    BorderColorProps,
    BorderWidthProps,
    BorderRadiusProps,
    BorderStyleProps,
    ZIndexProps {}

export const Box = styled('div')<BoxProps>(
  {
    boxSizing: 'border-box',
  },
  position,
  display,
  top,
  right,
  bottom,
  left,
  space,
  width,
  height,
  maxWidth,
  minWidth,
  colorStyle,
  color,
  backgroundColor,
  borderColor,
  borderWidth,
  borderRadius,
  borderStyle,
  zIndex
)

export default Box
