name: "Build and Archive Cactus"
description: "Builds all cactus modules and store their dist files in artifacts to share between jobs"
runs:
  using: "composite"
  steps: 
    - name: Build cactus-fwk
      run: yarn fwk build
      shell: bash

    - name: Build cactus-theme
      run: yarn theme build
      shell: bash
    
    - name: Build cactus-i18n
      run: yarn i18n build
      shell: bash

    - name: Build cactus-icons
      run: yarn icons build
      shell: bash

    - name: Build cactus-web
      run: yarn web build
      shell: bash

    - name: Build cactus-form
      run: yarn form build
      shell: bash
