import styled from 'styled-components'
import {
  position,
  top,
  bottom,
  right,
  left,
  width,
  maxWidth,
  minWidth,
  space,
  fontSize,
  color,
  colorStyle,
  borderColor,
  borderWidth,
  borderStyle,
  display,
  flex,
  alignItems,
  alignContent,
  justifyContent,
  flexWrap,
  flexBasis,
  flexDirection,
  justifySelf,
  alignSelf,
  order,
  zIndex,
  PositionProps,
  TopProps,
  BottomProps,
  LeftProps,
  RightProps,
  WidthProps,
  MaxWidthProps,
  MinWidthProps,
  SpaceProps,
  FontSizeProps,
  ColorProps,
  ColorStyleProps,
  DisplayProps,
  BorderColorProps,
  BorderWidthProps,
  BorderStyleProps,
  FlexProps,
  AlignItemsProps,
  AlignContentProps,
  JustifyContentProps,
  FlexWrapProps,
  FlexBasisProps,
  FlexDirectionProps,
  JustifySelfProps,
  OrderProps,
  AlignSelfProps,
  ZIndexProps,
} from 'styled-system'

interface BoxProps
  extends PositionProps,
    TopProps,
    BottomProps,
    LeftProps,
    RightProps,
    WidthProps,
    MaxWidthProps,
    MinWidthProps,
    SpaceProps,
    FontSizeProps,
    ColorProps,
    ColorStyleProps,
    DisplayProps,
    BorderColorProps,
    BorderWidthProps,
    BorderStyleProps,
    FlexProps,
    AlignItemsProps,
    AlignContentProps,
    JustifyContentProps,
    FlexWrapProps,
    FlexBasisProps,
    FlexDirectionProps,
    JustifySelfProps,
    OrderProps,
    AlignSelfProps,
    ZIndexProps {}

const Box = styled('div')<BoxProps>(
  {
    boxSizing: 'border-box',
  },
  position,
  top,
  right,
  bottom,
  left,
  space,
  width,
  fontSize,
  colorStyle,
  color,
  display,
  borderColor,
  borderWidth,
  borderStyle,
  flex,
  alignItems,
  alignContent,
  justifyContent,
  flexWrap,
  flexBasis,
  flexDirection,
  justifySelf,
  alignSelf,
  order,
  zIndex
)

export default Box
