const arizonaCities = [
  'Apache Junction',
  'Avondale',
  'Benson',
  'Bisbee',
  'Buckeye',
  'Bullhead City',
  'Camp Verde',
  'Carefree',
  'Casa Grande',
  'Cave Creek',
  'Chandler',
  'Chino Valley',
  'Clarkdale',
  'Clifton',
  'Colorado City',
  'Coolidge',
  'Cottonwood',
  'Dewey-Humboldt',
  'Douglas',
  'Duncan',
  'Eagar',
  'El Mirage',
  'Eloy',
  'Flagstaff',
  'Florence',
  'Fountain Hills',
  'Fredonia',
  'Gila Bend',
  'Gilbert',
  'Glendale',
  'Globe',
  'Goodyear',
  'Guadalupe',
  'Hayden',
  'Holbrook',
  'Huachuca City',
  'Jerome',
  'Kearny',
  'Kingman',
  'Lake Havasu City',
  'Litchfield Park',
  'Mammoth',
  'Marana',
  'Maricopa',
  'Mesa',
  'Miami',
  'Nogales',
  'Oro Valley',
  'Page',
  'Paradise Valley',
  'Parker',
  'Patagonia',
  'Payson',
  'Peoria',
  'Phoenix',
  'Pima',
  'Pinetop-Lakeside',
  'Prescott',
  'Prescott Valley',
  'Quartzsite',
  'Queen Creek',
  'Safford',
  'Sahuarita',
  'San Luis',
  'Scottsdale',
  'Sedona',
  'Show Low',
  'Sierra Vista',
  'Snowflake',
  'Somerton',
  'South Tucson',
  'Springerville',
  'St. Johns',
  'Star Valley',
  'Superior',
  'Surprise',
  'Taylor',
  'Tempe',
  'Thatcher',
  'Tolleson',
  'Tombstone',
  'Tucson',
  'Tusayan',
  'Wellton',
  'Wickenburg',
  'Willcox',
  'Williams',
  'Winkelman',
  'Winslow',
  'Youngtown',
  'Yuma',
]

export default arizonaCities
