name: CI Pipeline
on:
  push:
    branches:
    - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Version
        shell: bash
        run: node --version

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build Modules
        uses: ./.github/actions/cactus-build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Download built modules
        uses: ./.github/actions/download-dist-artifacts

      - name: Test Modules
        run: |
          yarn theme test:ci
          yarn fwk test:ci
          yarn i18n test:ci
          yarn form test:ci
          yarn icons test:ci
          yarn web test:ci

  integration-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Download built modules
        uses: ./.github/actions/download-dist-artifacts

      - name: Integration Tests
        uses: ./actions/integration-tests
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  
  visual-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Download built modules
        uses: ./.github/actions/download-dist-artifacts

      - name: Visual Tests
        uses: ./actions/storyshots

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Create Pull Request
        uses: ./actions/create-pull-request
        with:
          branch: ${{ steps.extract_branch.outputs.branch }}-patch

  docs-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Download built modules
        uses: ./.github/actions/download-dist-artifacts

      - name: Test Docs Website
        run: yarn docs test:ci
