name: CI Pipeline
on: push

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Get Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: NodeJS Version
        run: node --version

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Build cactus-fwk
        run: yarn fwk build

      - name: Build cactus-theme
        run: yarn theme build

      - name: Build cactus-i18n
        run: yarn i18n build

      - name: Build cactus-icons
        run: yarn icons build

      - name: Build cactus-web
        run: yarn web build

      - name: Test Packages
        run: yarn run test:ci
