name: CI Pipeline
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: NodeJS Version
        run: node --version

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Lint Packages
        run: yarn lint

      - name: Build cactus-fwk
        run: yarn fwk build

      - name: Build cactus-theme
        run: yarn theme build

      - name: Build cactus-i18n
        run: yarn i18n build

      - name: Build cactus-icons
        run: yarn icons build

      - name: Build cactus-web
        run: yarn web build

      - name: Test Modules
        run: |
          yarn theme test:ci
          yarn fwk test:ci
          yarn i18n test:ci
          yarn icons test:ci
          yarn web test:ci

      - name: Visual Tests
        uses: ./actions/storyshots

      - name: Integration Tests
        uses: ./actions/integration-tests
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}

      - name: Test Docs Website
        run: yarn docs test:ci
