name: Master Pipeline
on:
  push:
    branches:
      - master
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Publish the docs
      run: yarn docs:publish
