name: Master Pipeline
on:
  push:
    branches:
    - '**'
    tags-ignore:
      - '**'
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Git Config
      run: |
        git config user.name "Pipeline Bot"
        git config user.email "<>"

    - name: Install Packages
      run: yarn install --immutable

    - name: Build Packages
      run: yarn build

    - name: Build Documentation Site
      run: yarn docs build
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"

    - name: Publish Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/public
