name: Master Pipeline
on:
  push:
    branches:
      - master
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Packages
      run: yarn install --immutable
      
    - name: Build Packages
      run: yarn build

    - name: Publish the docs
      run: yarn docs:publish
