name: Master Pipeline
on:
  push:
    branches:
    - '**'
    tags-ignore:
      - '**'
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Decrypt secrets
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        openssl aes-256-cbc -in .github/workflows/secrets/cactus_auth.enc -out .github/workflows/secrets/cactus_auth -pass pass:$SSH_PRIVATE_KEY -d -md sha1

    - name: Setup SSH agent
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        chmod 0600 .github/workflows/secrets/cactus_auth
        ssh-add .github/workflows/secrets/cactus_auth

    - name: Install Packages
      run: yarn install --immutable

    - name: Build Packages
      run: yarn build

    - name: Build Documentation Site
      run: yarn docs build
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"

    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:repayci@github.com/${GITHUB_REPOSITORY}.git
        yarn gh-pages -d ./website/public -u "repayci <repayci@repay.com>"
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        NODE_OPTIONS: "--max_old_space_size=4096"

    - name: Cleanup
      if: always()
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-add -D
        rm -Rf *
