name: Snyk Scan
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  scan-if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk
        uses: ./actions/snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
